name: 'Generate docs'

on:
  push:
    branches:
      - main
    paths:
      - 'src/Microsoft.ComponentDetection.Orchestrator/ArgumentSets/*.cs'

permissions:
  contents: read

jobs:
  gen-docs:
    permissions:
      contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0

      - name: Generate docs
        run: |
          touch version.json
          touch version_dev.json
          
          # Run CLI
          dotnet run -p src/Microsoft.ComponentDetection help scan 2> help.txt || true
          cat <<EOF > docs/detector-arguments.md
          # Detector arguments
          
          \`\`\`shell
          dotnet run -p './src/Microsoft.ComponentDetection' help scan
          \`\`\`

          \`\`\`
          $(tail --lines=+4 help.txt)
          \`\`\`
          EOF

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: 'Update docs'
          file_pattern: '*.md'
